CREATE OR REPLACE PROCEDURE SHOW_PENDING_ORDERS IS
BEGIN
FOR I IN (SELECT * FROM orderss WHERE is_completed = 'N')LOOP
DBMS_OUTPUT.PUT_LINE('ORDER ID: '|| I.ORDER_ID ||',PERSON ID: '|| I.PERSON_ID||',ITEM: '|| I.ITEAM_NAME);
END LOOP;
END;

