CREATE OR REPLACE PROCEDURE TODAY_MENU IS
CURSOR C_TODAY_MENU IS
SELECT ITEM_NAME,PRICE 
FROM MENU
WHERE MENU_DATE = TRUNC(SYSDATE);

BEGIN
FOR I IN C_TODAY_MENU LOOP
DBMS_OUTPUT.PUT_LINE('ITEM: '|| I.ITEM_NAME ||',PRICE: '||I.PRICE);
END LOOP;
END;